---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result
  
- debug: var=result

- name: Delete instances
  os_server:
    name: "{{ item.name }}"
    cloud: openstack
    state: absent
  loop: "{{ result.openstack_servers }}"
