- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Fetch OpenStack servers
    os_server_info:
      cloud: openstack
    register: result

  - name: Set frontend server ip address fact
    set_fact: 
       frontend_ip: "{{ item.public_v4 }}"
    when: item.name=='frontend'
    with_items: "{{result.openstack_servers}}"

  - debug: var=frontend_ip

  - name: Curl frontend website
    uri:
      url: "http://{{ frontend_ip }}/"
      return_content: yes
      status_code: 200
    register: webpage

  - debug:
      msg: "{{ webpage }}"

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
